# Travis build config
sudo: false
language: node_js
node_js:
  - "5.10.1"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test
  - NODE_ENV=development npm run deploy
  - NODE_ENV=staging npm run deploy
  - NODE_ENV=production npm run deploy

after_success:
  - npm run codecov
